application:
  courses:
    paths:
      git: courses
      externalCode: temp
      dependencies: server/dependencies
  profiling: false
  security:
    expirationTime: 864_000_00
    secret: ThisIsASecret
    tokenPrefix: Bearer
    headerString: Authorization
    responseHeaders:
      accessControlAllowOrigin: http://localhost:8081
      accessControlAllowCredentials: true
      accessControlExposeHeaders: Access-Token, Authorization

email:
    server: "http://localhost:8080"
    user: "studyartteam@gmail.com"
    password: "pass_for_study"
    host: smtp.gmail.com
    port: 587
    properties:
      smtp:
        auth: true
        starttls.enable: true

maven:
    dependenciesPath: dependencies
    goals:
      copyToDirectory: dependency:copy-dependencies -DoutputDirectory=
    embedded:
      path: /home/v21k/dev/projects/StudyArt/server/mvnw

spring:
  datasource:
    url: jdbc:h2:file:./db/studyArt;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      # console view at localhost:8080/console
      path: /console

logging:
  level:
    org.springframework.web : INFO
    ua.artcode: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/logs.log